theme: minima
title: Learn GitHub Pages with Jekyll
author: JW Lee
email: dharana0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Pages is an easy way to create a host.
  Learning GitHub Pages using GitHub learning lab.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jongweon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
